services:
  - type: web
    name: Ewaste-backend
    env: python
    plan: free
    buildCommand: bash ./build.sh
    startCommand: gunicorn backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://ewaste-lemon.vercel.app
      - key: FRONTEND_ORIGINS
        value: https://ewaste-lemon.vercel.app
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://ewaste-lemon.vercel.app
      - key: DJANGO_SESSION_COOKIE_SAMESITE
        value: None
      - key: DJANGO_CSRF_COOKIE_SAMESITE
        value: None
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: MIGRATION_DATABASE_URL
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        value: raya@ex.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: raya@ex.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Raya@123
